= Standards, Reference and Guidance Documents

== References
 * https://nso.nato.int/nso/nsdd/stanagdetails.html?idCover=8285&LA=EN[STANAG 4603 Ed 2] - https://standards.ieee.org/findstds/standard/1516-2010.html[IEEE 1516-2010 - High Level Architecture (HLA)]
 * https://nso.nato.int/nso/nsdd/stanrecdetails.html?idCover=8834[STANREC 4800 Ed 1]- https://nso.nato.int/nso/nsdd/APdetails.html?APNo=2268&LA=EN[AMSP-04 Ed A - NATO Education and Training Network Federation Architecture and Federation Object Model Design]
 	* [AMSP-04 NETN FAFD FOM Modules](https://www.sto.nato.int/pages/natostandards.aspx)
 * [STANAG 2019 Ed.: 7](https://nso.nato.int/nso/nsdd/stanagdetails.html?idCover=8552&LA=EN) - [APP-6 Ed D - NATO Joint Military Symbology](https://nso.nato.int/nso/nsdd/apdetails.html?APNo=1912)
* **C-BML**
 * [SISO-STD-011-2014: Standard for Coalition Battle Management Language (C-BML) Phase 1, Version 1.0 (14 Apr 2014)](https://www.sisostds.org/ProductsPublications/Standards/SISOStandards.aspx)
 * [SISO-GUIDE-004-2017: Guide for Coalition Battle Management Language (C-BML) Phase 1](https://www.sisostds.org/ProductsPublications/GuidanceProducts.aspx)
* **MSDL**
 * [SISO-STD-007-2008: Standard for Military Scenario Definition Language (MSDL) (reaffirmed 11 May 2015)](https://www.sisostds.org/ProductsPublications/Standards/SISOStandards.aspx)
* **HLA**
 * [IEEE 1516-2010 IEEE Standard for Modeling and Simulation (M&S) High Level Architecture (HLA) -- Framework and Rules](https://standards.ieee.org/findstds/standard/1516-2010.html)
 * [IEEE 1516.1-2010  IEEE Standard for Modeling and Simulation (M&S) High Level Architecture (HLA) -- Federate Interface Specification](https://standards.ieee.org/develop/project/1516.1.html)
 * [IEEE 1516.2-2010  IEEE Standard for Modeling and Simulation (M&S) High Level Architecture (HLA) -- Object Model Template (OMT) Specification](https://standards.ieee.org/develop/project/1516.2.html)
* **RPR-FOM**
 * [SISO-STD-001-2015: Standard for Guidance, Rationale, and Interoperability Modalities (GRIM) for the Real-time Platform Reference Federation Object Model (RPR FOM), Version 2.0 (10 Aug 2015)](https://www.sisostds.org/ProductsPublications/Standards/SISOStandards.aspx)
 * [SISO-STD-001.1-2015: Standard for Real-time Platform Reference Federation Object Model (RPR FOM), Version 2.0 (10 Aug 2015) ](https://www.sisostds.org/ProductsPublications/Standards/SISOStandards.aspx)
 * [SISO-REF-010-2017: Reference for Enumerations for Simulation Interoperability](https://www.sisostds.org/ProductsPublications/ReferenceDocuments.aspx)

== Bibliography

Öhlund G., Löfstrand B., Hassaine F. (2007) **Knowledge Network for Federation Architecture and Design**. In: Proceedings from 2007 Fall Simulation Interoperability Workshop. 07F-SIW-024. - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=27765) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=27766)

Huiskamp W., Loper M., Cutts D. (2007) **Federation Agreements - Observations, Considerations and Proposals out of the NATO MSG-052 Working Group “Knowledge Network for Distributed simulation Architecture and Design”**. In: Proceedings from Fall 2007 Simulation Interoperability Workshop. 07F-SIW-058. Simulation Interoperability Standards Organization - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=27813)

Huiskamp W., Cutts D., Chaigneau S. (2008) **Improving the Federation Agreements Definition. New Proposals Out of the NATO MSG-052 Working Group “Knowledge Network for Federation Architecture and Design”**. In: The NATO Modelling and Simulation Group (NMSG) Symposium (MSG-060) “How is Modelling and Simulation meeting the Defence Challenges”, Vancouver, Canada, October 2008. RTO-MP-MSG-060-02 - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/Forms/All%20MPs.aspx?FolderCTID=0x0120D5200078F9E87043356C409A0D30823AFA16F602008CF184CAB7588E468F5E9FA364E05BA5&View=%7B72ed425f-c31f-451c-a545-41122bba61a7%7D&RootFolder=%2Fpublications%2FSTO%20Meeting%20Proceedings%2FRTO-MP-MSG-060&TreeField=Folders&TreeValue=RTO-MP-MSG-060&ProcessQStringToCAML=1&SortField=DocIcon&SortDir=Asc)

Löfstrand B., Khayari R., Keller K., Greiwe K., Meyer zu Drewer P., Hultén T., Bowers A., Faye J. P., (2009) **Logistics FOM Module in Snow Leopard: Recommendations by MSG-068 NATO Education and Training Network Task Group**. In: Proceedings of 2009 Fall Simulation Interoperability Workshop, 09FF-SIW-076. September 2009. - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=28764) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=28765).

Cayirci E., Rong C., Huiskamp W., Verkoelen C. (2009) **Snow Leopard Cloud: A Multi-national Education Training and Experimentation Cloud and Its Security Challenges**. In: Jaatun M.G., Zhao G., Rong C. (eds) Cloud Computing. CloudCom 2009. Lecture Notes in Computer Science, vol 5931. Springer, Berlin, Heidelberg. - [Paper](https://www.semanticscholar.org/paper/Snow-Leopard-Cloud%3A-A-Multi-national-Education-and-Cayirci-Rong/a21a57bb01e1395bc8bbaefd63e701c7f1d41514?tab=abstract).

Ruiz J., Désert D., Guillou P. (2012) **Improvement of simulation interoperability by introducing the CBML benefits into the HLA world**. In: Proceedings of 2012 Fall Simulation Interoperability Workshop, 12F-SIW-009, Simulation Interoperability Standards Organization, September 2012 - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41338)
& [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41337)

Alstad A, Løvlid R. A., Mevassvik O. M., Nielsen M. N., Henderson H. C., Jansen R. E. J., de Reus N. M. (2013) **Low-level Battle Management Language**. In: Proceedings of 2013 Spring Simulation Interoperability Workshop, 13S-SIW-032, Simulation Interoperability Standards Organization, April 2013 - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41486) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41485)

Ruiz J., Désert D., Hubervic A., Guillou P., Jansen R. E. J., de Reus N. M., Henderson H. C., Fauske K. M., Olsson L. (2013) **BML and MSDL for multi-level simulations**. In: Proceedings of 2013 Fall Simulation Interoperability Workshop, 13F-SIW-002, Simulation Interoperability Standards Organization, September 2013 - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41537) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=41536)

Nyløkke J., Horn B., Roos K., Solum E., Horn K., Newton N., Krarup-Hansen N., Morris S. (2014) **Interoperability and harmonization analysis of the German Maritime Federation Object Model (GMF) in relation to SISO RPR FOM with possible extensions in a multinational forum**. In: Proceedings of 2014 Fall Simulation Interoperability Workshop, 14F-SIW-004. Simulation Interoperability Standards Organization - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=42348)

Lloyd J., Newton N., Mifsud M., Ruiz J., Désert D., Hubervic A., Olsson L (2014) **Chemical Biological Radiological modelling capability: UK and NATO HLA Evolved experimentation**. In: Proceedings of 2014 Fall Simulation Interoperability Workshop. 14F-SIW-021. Simulation Interoperability Standards Organization - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=42367) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=42366)

Tard L. (2014) **SPHINX: a Web-Based Tool for CAX Preparation and Capitalization**. NATO Modelling and Simulation Group (NMSG) Multi-Workshop MSG-126, STO-MP-MSG-126-014. - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-126/MP-MSG-126-14.pdf)

Mifsud M., Löfstrand B., Lloyd J. (2014) **An update on the developments and maturity of the NATO Education and Training Network (NETN) Federation Architecture and Federation Object Model (FOM)** NATO Modelling and Simulation Group (NMSG) Multi-Workshop MSG-126, STO-MP-MSG-126-022. - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-126/MP-MSG-126-22.pdf)

Löfstrand B. (2014) **NATO Education and Training Network - Federation Architecture and FOM Design (NETN FAFD v2.0)**. Presentation at 9th CAX Forum 2014

Löfstrand B., Hodicky J. (2015) **NATO Distributed Simulation Architecture & Design, Compliance Testing and Certification - MSG-134** Presentation at 10th NATO CAX Forum 2015. September 2015

Herzog R., Johannes Mulder J., Horst Behner H., Löfstrand B. (2015) **A Safe Way to Reliable Federations** STO-MP-MSG-133-021. NMSG Symposium on M&S Support to Operational Tasks including War Gaming, Logistics, Cyber Defence. October 2015. Munich, Germany - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-133/MP-MSG-133-21.doc) & [Presentation](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-133/SupportingDocuments.zip)

Löfstrand B., Behner H. (2016) **MSG-134 CONOPS, Business Model and Recommendations** Modelling and Simulation Standards Subgroup (MS3) meeting at NMSG 37th Business Meeting. June 2016. Rome, Italy

Ruiz J., Behner H., Herzog R., Hodicky J., Löfstrand B., Vrieler S. (2016) **Towards a new NATO certification capability for HLA interoperability** In: Proceedings of 2016 Simulation Innovation Workshop, 2016-SIW-004. Simulation Interoperability Standards Organization - [Paper](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=44865) & [Presentation](https://www.sisostds.org/DigitalLibrary.aspx?Command=Core_Download&EntryId=44966)

Jan Hodicky J., Stefan Vrieler S. (2017) **Establishment of HLA compliance certification within NATO** SISO Seminar at ITEC 2017. May 2017. Rotterdam, Netherlands

Behner H., Löfstrand B. (2017) **The New HLA Certification Process in NATO** MSG-149 Symposium on M&S Technologies and Standards for Enabling Alliance Interoperability and Pervasive M&S Applications. MP-MSG-149-19. ISBN 978-92-837-2137-6. Lisbon, October 2017 - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-149/MP-MSG-149-19.pdf)

Löfstrand B. (2017) **NATO Education and Training Network Federation Architecture and FOM Design (NETN FAFD)** Presentation at 12th CAX Forum. Florence. September 2017 - [Presentation](https://www.mscoe.org/document/1177/download/).

Behner H., Löfstrand B. (2017) **Establishing a HLA Certification Process in NATO** Paper 17058. Interservice/ Industry Training, Simulation and Education Conference. Harnessing new technologies to win in a complex world. November 2017 - [Paper](http://www.iitsecdocs.com/download/2017/2017_17058)

Löfstrand B. (2018) **NATO HLA Certification of Compliance with STANREC 4800 : AMSP-04 NETN FAFD** Presentation at 13th CAX Forum. Sofia. September 2018. 

Löfstrand B. (2018) **STANREC 4800 - AMSP-04 NATO Education and Training Network Federation Agreement and FOM Design** NMSG Symposium. Multinational Interoperability: Agility for Military Training and Operational Applications Innovation in Enterprise Level Consortiums and M&S Technology Development. MP-MSG-159-12. ISBN 978-92-837-2197-0. Ottawa. October 2018. - [Paper](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-159/MP-MSG-159-12.pdf) & [Presentation](https://www.sto.nato.int/publications/STO%20Meeting%20Proceedings/STO-MP-MSG-159/MP-MSG-159-12P.pdf).
